sudo: false
language: python
cache: pip
python:
    - '2.7'
script:
    - 'make test'
after_success:
    - 'pip install coveralls'
    - 'coveralls'
branches:
    only:
      - 'master'
env:
    - TOXENV=py27-dj14
    - TOXENV=py27-dj18
